name: Sample
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@871daa956ca9ea99f3c3e30acb424b7960676734 # v5.0.0
      with:
        python-version: "3.10"
    - run: echo ${{github.repository}}
      shell: bash
